//USERACCOUNT
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const PATCH_USER = "PATCH_USER";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const FACEBOOK_AUTH_SUCCESS = "FACEBOOK_AUTH_SUCCESS";
export const FACEBOOK_AUTH_FAIL = "FACEBOOK_AUTH_FAIL";

//HOTEL
export const GET_HOTELS = "GET_HOTELS";
export const GET_HOTELS_BY_PARTNER = "GET_HOTELS_BY_PARTNER";
export const SEARCH_HOTELS = "SEARCH_HOTELS";
export const GET_HOTEL_BY_ROOM_ID = "GET_HOTEL_BY_ROOM_ID";
export const POST_HOTEL = "POST_HOTEL";
export const PATCH_HOTEL = "PATCH_HOTEL";
export const DELETE_HOTEL = "DELETE_HOTEL";

//HOTEL IMAGE
export const GET_HOTEL_IMAGES = "GET_HOTEL_IMAGES";
export const GET_HOTEL_IMAGES_BY_HOTEL_ID = "GET_HOTEL_IMAGES_BY_HOTEL_ID";
export const POST_HOTEL_IMAGE = "POST_HOTEL_IMAGE";
export const PATCH_HOTEL_IMAGE = "PATCH_HOTEL_IMAGE";
export const DELETE_HOTEL_IMAGE = "DELETE_HOTEL_IMAGE";

//ROOM
export const GET_ROOMS = "GET_ROOMS";
export const GET_ROOMS_BY_HOTEL_ID = "GET_ROOMS_BY_HOTEL_ID";
export const GET_ROOM_BY_ID = "GET_ROOM_BY_ID";
export const POST_ROOM = "POST_ROOM";
export const PATCH_ROOM = "PATCH_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";

//ROOM IMAGE
export const GET_ROOM_IMAGES = "GET_ROOM_IMAGES";
export const POST_ROOM_IMAGE = "POST_ROOM_IMAGE";
export const DELETE_ROOM_IMAGE = "DELETE_ROOM_IMAGE";

//HOTEL ADDRESS
export const GET_ADDRESSES = "GET_ADDRESSES";
export const POST_ADDRESS = "POST_ADDRESS";
export const PATCH_ADDRESS = "PATCH_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";

//HOTEL AMENITIY
export const GET_HOTEL_AMENITIES = "GET_HOTEL_AMENITIES";
export const POST_HOTEL_AMENITY = "POST_HOTEL_AMENITY";
export const PATCH_HOTEL_AMENITY = "PATCH_HOTEL_AMENITY";
export const DELETE_HOTEL_AMENITY = "DELETE_HOTEL_AMENITY";

//ROOM AMENITIY
export const GET_ROOM_AMENITIES = "GET_ROOM_AMENITIES";
export const POST_ROOM_AMENITY = "POST_ROOM_AMENITY";
export const PATCH_ROOM_AMENITY = "PATCH_ROOM_AMENITY";
export const DELETE_ROOM_AMENITY = "DELETE_ROOM_AMENITY";

//BOOKING
export const GET_BOOKINGS = "GET_BOOKINGS";
export const GET_BOOKINGS_BY_USER = "GET_BOOKINGS_BY_USER";
export const GET_BOOKINGS_BY_PARTNER = "GET_BOOKINGS_BY_PARTNER";
export const GET_BOOKINGS_BY_ROOM = "GET_BOOKINGS_BY_ROOM";
export const POST_BOOKING = "POST_BOOKING";
export const PATCH_BOOKING = "PATCH_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";

//SAVED_HOTEL
export const GET_SAVED_HOTELS_BY_USER = "GET_SAVED_HOTELS_BY_USER";
export const POST_SAVED_HOTEL = "POST_SAVED_HOTEL";
export const DELETE_SAVED_HOTEL = "DELETE_SAVED_HOTEL";

//COMMENT
export const GET_COMMENTS_BY_USER = "GET_COMMENTS_BY_USER";
export const GET_COMMENTS_BY_HOTEL = "GET_COMMENTS_BY_HOTEL";
export const POST_COMMENT = "POST_COMMENT";
export const PATCH_COMMENT = "PATCH_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
