# Generated by Django 3.2 on 2021-05-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20210520_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Hotel Services', 'Hd'), ('Food and Drinks', 'Fd'), ('Things to Do', 'Ttd'), ('Public Facilities', 'Pf'), ('In-room Facilities', 'Irf'), ('General', 'Gen'), ('Sports and Recreations', 'Sr'), ('Transportation', 'Trsp'), ('Nearby Facilities', 'Nf'), ('Business Facilities', 'Bf'), ('Family-friendly Facilities', 'Fff'), ('Connectivity', 'Cnn'), ('Shuttle Service', 'Ss'), ('Others', 'Others')], default='Others', max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
