# Generated by Django 3.2 on 2021-05-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_roomamenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelamenity',
            name='category',
            field=models.CharField(choices=[('Hotel Services', 'Hotel Services'), ('Food and Drinks', 'Food And Drinks'), ('Things to Do', 'Things To Do'), ('Public Facilities', 'Public Facilities'), ('In-room Facilities', 'In Room Facilities'), ('General', 'General'), ('Sports and Recreations', 'Sports And Recreations'), ('Transportation', 'Transportation'), ('Nearby Facilities', 'Nearby Facilities'), ('Business Facilities', 'Business Facilities'), ('Family-friendly Facilities', 'Family Friendly Facilities'), ('Connectivity', 'Connectivity'), ('Shuttle Services', 'Shuttle Services'), ('Others', 'Others')], default='Others', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roomamenity',
            name='category',
            field=models.CharField(choices=[('Facilities', 'Facilities'), ('Amenities', 'Amenities'), ('Others', 'Others')], default='Others', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RoomAmenityAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_amenity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.roomamenity')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.room')),
            ],
        ),
        migrations.CreateModel(
            name='HotelAmenityAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_amenity_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotelamenity')),
                ('hotel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
    ]
