# Generated by Django 3.2 on 2021-05-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_auto_20210528_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('room_id', models.CharField(max_length=50)),
                ('hotel_id', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('payment_time', models.DateTimeField(null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.booking')),
            ],
        ),
    ]
