# Generated by Django 3.2 on 2021-06-02 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_alter_comment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='booking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.booking'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
