# Generated by Django 3.2 on 2021-06-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_auto_20210602_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guest',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
