# Generated by Django 3.2 on 2021-06-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_auto_20210604_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='business_license',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
