# Generated by Django 3.2 on 2021-06-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_auto_20210606_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hotel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotels.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
