# Generated by Django 3.2 on 2021-06-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_auto_20210608_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='sub_name',
        ),
    ]
